- tasks:
  - type: opspace::OrientationTask
    name: eeori_shake
    end_effector_id: 6
    sigma_threshold: 0.01
    kp: 800.0
    kd: 20.0
    maxvel: 12.0
  - type: opspace::CartPosTrjTask
    name: eepos_shake
    end_effector_id: 6
    sigma_threshold: 0.005
    control_point: [ 0.0, 0.0, 0.0 ]
    dt_seconds: 0.0025
    kp: [ 60.0 ]
    kd: [ 12.0 ]
    maxvel: [ 0.8 ]
    maxacc: [ 2.4 ]
  - type: opspace::JPosTrjTask
    name: posture_shake
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 150.0 ]
    kd: [  10.0 ]
    maxvel: [ 1.0 ]
    maxacc: [ 6.0 ]
  - type: opspace::CartPosTrjTask
    name: eepos_wave
    end_effector_id: 6
    sigma_threshold: 0.005
    control_point: [ 0.0, 0.0, 0.0 ]
    dt_seconds: 0.0025
    kp: [ 25.0 ]
    kd: [  5.0 ]
    maxvel: [ 0.8 ]
    maxacc: [ 2.4 ]
  - type: opspace::JPosTrjTask
    name: posture_wave
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 150.0 ]
    kd: [  10.0 ]
    maxvel: [ 1.0 ]
    maxacc: [ 6.0 ]

- skills:
  - type: uta_opspace::HelloGoodbyeSkill
    name: hello_goodbye
    slots:
      # shake_orientation: eeori_shake
      shake_position: eepos_shake
      shake_posture: posture_shake
      wave_position: eepos_wave
      wave_posture: posture_wave
      