- tasks:
  - type: opspace::JPosTask
    name: joint_posture
    sigma_threshold: 0.0001
    kp: [ 150.0, 150.0, 150.0, 150.0, 150.0, 150.0, 150.0 ]
    kd: [  10.0 ]
    maxvel: [ 9 ]

- skills:
  - type: opspace::GenericSkill
    name: generic_skill
    slots:
    - task: joint_posture
