- tasks:
  - type: opspace::JPosTrjTask
    name: joint_posture
    sigma_threshold: 0.0001
    dt_seconds: 0.0025
    kp: [ 150.0, 150.0, 150.0, 150.0, 600.0, 150.0, 150.0 ]
    kd: [  10.0 ]
    maxvel: [ 3.0 ]
    maxacc: [ 6.0 ]

- skills:
  - type: opspace::GenericSkill
    name: generic_skill
    slots:
    - task: joint_posture
