- tasks:
  - type: opspace::OrientationTask
    name: end_effector_orientation
    end_effector_id: 6
    sigma_threshold: 0.0001
    kp: 600.0
    kd: 10.0
    maxvel: 12.0
  - type: opspace::JPosTask
    name: joint_posture
    sigma_threshold: 0.0001
    kp: [ 0.0 ]
    kd: [ 3.0 ]
    maxvel: [ 10.0 ]

- skills:
  - type: opspace::GenericSkill
    name: generic_skill
    slots:
    - task: end_effector_orientation
    - task: joint_posture
